name1 = prompt("Enter your name")
weight = prompt("Enter your weight ")
height  = prompt("Enter your height ")
BMI = weight / (height * height)
document.write (name1 + "YOUR BMI IS  " + BMI)
alert (name1 +"YOUR BMI IS  " + BMI)
console.log  (name1 + "YOUR BMI IS " +BMI)